name: Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  
jobs:
  build:
    name: make snake
    runs-on: ubuntu-latest

    steps:
      - name: look at repo
        uses: actions/checkout@v4

      - name: generate snake anim
        uses: Platane/snk@v3
        with:
          github_user_name: riicess
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-ocean.gif?color_snake=#9C27B0&color_dots=#BB86FC

      - name: push the thingy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
